CREATE TABLE Team
(
	TeamID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Location VARCHAR(50) NOT NULL
);

CREATE TABLE Player
(
	PlayerID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Height INT,
	Weight INT,
	dateofBirth DATETIME NOT NULL
);

CREATE TABLE Matchup
(
	MatchupID INT IDENTITY(1,1) PRIMARY KEY,
	StadiumID INT FOREIGN KEY REFERENCES Stadium(StadiumID),
	homeTeamID INT NOT NULL,
	awayTeamID INT NOT NULL,
	StatsID INT FOREIGN KEY REFERENCES Stats(StatsID),
	winninTeamID INT,
	Date DATETIME NOT NULL
);

CREATE TABLE Stadium
(
	StadiumID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Address VARCHAR(100) NOT NULL
);

CREATE TABLE Stats
(
	StatsID INT IDENTITY(1,1) PRIMARY KEY,
	MatchupID INT FOREIGN KEY REFERENCES Matchup(MatchupID),
	TeamID INT FOREIGN KEY REFERENCES Team(TeamID),
	offensiveYards INT,
	Turnovers INT
);

CREATE TABLE Roster
(
	beginDate DATETIME NOT NULL,
	PlayerID INT FOREIGN KEY REFERENCES Player(PlayerID),
	endDate DATETIME,
	TeamID INT FOREIGN KEY REFERENCES Team(TeamID),
	Position VARCHAR(50),
	PRIMARY KEY (beginDate, PlayerID)
);