# Generated by Django 2.0.4 on 2018-04-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='matchID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Matchup'),
        ),
        migrations.AddField(
            model_name='score',
            name='teamID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Team'),
        ),
    ]
