# Generated by Django 2.0.4 on 2018-04-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180420_2254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('matchID', 'teamID')},
        ),
    ]
