# Generated by Django 2.0.4 on 2018-04-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20180420_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='matchID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Matchup'),
        ),
        migrations.AddField(
            model_name='stat',
            name='offensiveYards',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='stat',
            name='teamID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='stat',
            name='turnOvers',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together={('matchID', 'teamID')},
        ),
    ]
